### ISSUE TITLE
Lumira Designer 2 SP02

### ISSUE THREAD

**Issue by NeilTGG** [org-scn-design-studio-community/lumiradesignercommunityext#1]
Hi Mike and Co,
Just having a look at the Kpi Tile 2.0 in Lumira Designer 2 SP02 and comparing it to 1.6 . In the default tile, it seems to be missing the last x and y values, missing colours and chart lines seem also displaced. Please see:
![kpitile2_cf](https://user-images.githubusercontent.com/31236898/29553771-04c791c2-8760-11e7-8ef8-7ba3643e724e.jpg)
Any info on this is greatly appreciated,
Thanks.

**Comment by entmike** [comment]
Hi Neil,

Is it possible you can share me a sample app?

**Comment by entmike** [comment]
I figured it out....  You must run Blue Crystal theme.  In Lumira 2.0, it appears that the default newer 'Belize' theme doesn't work with these micro charts.

**Comment by NeilTGG** [comment]
Hi Mike,
Changing the Theme to Blue Crystal worked. 
Thanks heaps for looking into this one and resolving.
Cheers,
-Neil
