### ISSUE TITLE
Component Manager functions not working

### ISSUE THREAD

**Issue by philipphell** [org-scn-design-studio-community/lumiradesignercommunityext#10]
Hi, 
i've installed the extensions on a Lumira Designer SP2. 
When i use COMPONENTMANAGER component list functions and exists functions will not work. 

Other functions (get, set, returnAs) work. 
I use Lumira Designer in local mode. 

thanks for support

**Comment by entmike** [comment]
Hi, this is a component Karol wrote, so it may take me a bit to debug.  Can you share a simple example app, and/or the error log?  Hopefully this is something simple with the scope changes SAP did..

**Comment by entmike** [comment]
Ok, I've researched this.  We were using an undocumented hack in Design Studio prior to 2.0 that allowed us to iterate over global scope to determine a list of components in both the Component Manager and Component Layouter extensions.  Unfortunately, SAP has changed scope in the RhinoJS VM, and made this hack unusable.  I'm at a dead-end for now on this one.

**Comment by entmike** [comment]
Good news - I think I have come up with a new hack to test this.  Can you please re-test?

EDIT: Component Layouter is working, I have to do a few different things for Component Manager, stand by...

**Comment by entmike** [comment]
Ok, now it should be for sure fixed, if you would like to re-test.

**Comment by philipphell** [comment]
Hi, very cool.
 I testet the function listAllComponents(); sucessfully. 
Function listAllDataSources(); still does nothing. 
Do you have an idea ?

**Comment by entmike** [comment]
I will take a look, I did not try with data sources.  Hopefully a quick/easy fix.

**Comment by entmike** [comment]
Ok, I think I have listAllDataSources method fixed as well, now.  Can you re-download and try again and let me know?

**Comment by entmike** [comment]
I'll assume no news is good news and close this one EOD today.

**Comment by entmike** [comment]
Closing.
