### ISSUE TITLE
Donut not supported in sapui5m in design studio or lumira designe

### ISSUE THREAD

**Issue by lakshmikanthbouvet** [org-scn-design-studio-community/lumiradesignercommunityext#16]
In lumira designer when i have downloaded the org.scn community basics SDK, donut was not part of the compoenents..Do we have any alternative approach to get donut in to lumira designer?
![donut_compoenent](https://user-images.githubusercontent.com/33628495/32733465-9bef89a4-c88f-11e7-850a-a4490b391d71.png)

**Comment by MartinPankraz** [comment]
Hi lakshmikanthbouvet,

as you noticed already UI5 components from the sap.ui.commons library are no longer supported in Lumira 2.x. Unfortunately the sap.viz.ui5 library is not accessible either. So there is no plain UI5 way to do this anymore. Older dashboards using the sap.ui.commons.donut should still work in legacy mode in Lumira 2.x.

You need to load the necessary UI5 libraries yourself or use a non-sap library for your donut.

A standard-compliant way would be to use the standard Info Chart with type "Doughnut", which I recommend over any SDK hacks.

Kind regards
Martin
