### ISSUE TITLE
Missing Constraint for com.sap.db.jdbc

### ISSUE THREAD

**Issue by mkraai** [org-scn-design-studio-community/lumiradesignercommunityext#24]
Hi Mike,

As I only need one of the SDK components I wanted to look into splitting up the package so I can export only the one I need. As I'm new to SDKs I started with the SDK samples (to figure out how everything works) and followed the designer guide. I've installed everything required but when I try to run an sdk, e.g. coloredbox, then I keep getting the same message.

![eclipse message](https://user-images.githubusercontent.com/34571373/34038717-9c69fdf8-e18d-11e7-980d-5079f356fb98.PNG)

Does this issue seem familiar to you? I also get the message with the community SDKs. 

The things I've installed:
Java SE Development Kit 9.0.1
SBOP LUMIRA DESIGNER 2.0 SP03 
Eclipse IDE for Java EE Developers (64 bit)
LUM_20SP03_DS_SDK_SAMPLES

The target platform is also set correct, as is the XML catalog. I also couldn't really find a solution on the internet so I hope you can help me.

If you need more details, please let me know.

Thanks,
Maartje

**Comment by entmike** [comment]
I get that on 2 machines but not others. I’ve been able to safely click continue and ignore it and Lumira designer runs anyway.

**Comment by mkraai** [comment]
OK, good to know. Unfortunately with me it does not, but then it most likely has a different cause. Attached is the error.
[error.txt](https://github.com/org-scn-design-studio-community/lumiradesignercommunityext/files/1562678/error.txt)

**Comment by mkraai** [comment]
Apparently you need JDK8, 9 seems to have a bug/incompatibility issues. With 8 everything works fine
