### ISSUE TITLE
Empty JSON string (DATAITERATOR_ROLLING.flatten()#13

### ISSUE THREAD

**Issue by lalohv** [org-scn-design-studio-community/lumiradesignercommunityext#33]
Using a data iterator with DS from universe only instancing the method .getRows() I get this error 

The environment is SAP BOBJ 4.2 SP 100 and Lumira Server 2.1 SP1 with Lumira designer 2.1 SP1
[TRACE.txt](https://github.com/org-scn-design-studio-community/lumiradesignercommunityext/files/2138238/TRACE.txt)

**Comment by ncodernet** [comment]
Hello,
please consider replacing Data Iterator with official getDataSelections API. For details please see https://blogs.sap.com/2017/12/19/dynamic-apps-in-lumira-2.1-iterating-over-a-resultset/ .
The issue might come from the fact that many Universe data sources are master-data-only (having no measures).
The Data Iterator component would need to be corrected supporting such result sets - use selectionShape=3. In Design Studio 1.6 such result sets were never supported, but did work in some cases.

Reiner.

**Comment by lalohv** [comment]
Hi, thank you for the info. I used the getDataSelections API and it works. 
I will have in mind that exception.

Eduardo
