### ISSUE TITLE
The extension is not valid, Please upload a valid extension -- Error 

### ISSUE THREAD

**Issue by thumalur** [org-scn-design-studio-community/lumiradesignercommunityext#37]
Hi Team,

I was trying to install org.scn.community.sdk.extensions on SAP BO 4.2 SP05 PATCH04, but getting an error "**The extension is not valid, Please upload a valid extension**"; whereas able to install on the LUMIRA DESIGNER 2.1 SP1 Patch1.

Error MSG:
![image](https://user-images.githubusercontent.com/41346378/42844248-5ce24e8c-89e0-11e8-9335-a920ca38f41b.png)

LUMIRA DESIGNER 2.1SP1P1
![image](https://user-images.githubusercontent.com/41346378/42844201-3d78d818-89e0-11e8-931f-ddf2af531fc6.png)

your help much appreciated.

Warm Regards
Amar

**Comment by ncodernet** [comment]
Can you upload it from Designer?

**Comment by thumalur** [comment]
Hi Reiner Hille-Doering

Yes able to upload from Designer and able to see list of components

![image](https://user-images.githubusercontent.com/41346378/42846055-c91c2c80-89e5-11e8-80fb-33a6c40795e6.png)

but same components are not getting loaded from SAP BO 4.2 SP05PT4 CMC, thrown an error.

Warm Regards
Amar

**Comment by ncodernet** [comment]
Sure - I mean can you deploy the extension to BIP using the Dialog of your second screenshot. In Design Studio you always needed to install and   deploy via Designer. The Web-UI from first screenshot was added with 2.0 and might have issues.

**Comment by thumalur** [comment]
Thank you  Reiner Hille-Doering :+1:  your are awesome 

"Install on Platform" button was disabled with Developer's login

![image](https://user-images.githubusercontent.com/41346378/42882747-8aa41206-8a67-11e8-86ba-2d45135d6499.png)

Then i tired with Admin id  and able to "install on Platform". 

![image](https://user-images.githubusercontent.com/41346378/42885002-d8716230-8a6d-11e8-80b8-78a93a0e791f.png)

Warm Regards
Amar
