### ISSUE TITLE
Rapid Prototype functionalities missing

### ISSUE THREAD

**Issue by vijaybalagopala** [org-scn-design-studio-community/lumiradesignercommunityext#7]
Hi,

 We have been using the visibility property of the Rapid Prototype component on Design Studio 1.6 and recently upgraded to the Lumira 2.0. However, the setVisible property of the Rapid Prototype went missing on the component. Any reason why or is there something I missed?

**Comment by entmike** [comment]
Are you using VBI extensions by chance?

https://answers.sap.com/questions/314358/setvisible-property-is-not-working-after-installin.html

**Comment by entmike** [comment]
Closing because I've not heard any more details.
